// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqkIodTY8hLIQGoQ2EDCz9NIKizF8Opv0',
    appId: '1:929254290761:web:b0bd3dabff03554cac9698',
    messagingSenderId: '929254290761',
    projectId: 'financial-managememt-app',
    authDomain: 'financial-managememt-app.firebaseapp.com',
    storageBucket: 'financial-managememt-app.appspot.com',
    measurementId: 'G-1PW46YK7XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwTkicD1m3HWC6dRovQiJ85UyclYe9sWs',
    appId: '1:929254290761:android:f3505ed4c8eedf01ac9698',
    messagingSenderId: '929254290761',
    projectId: 'financial-managememt-app',
    storageBucket: 'financial-managememt-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7rXS6TDV7jOiyj1q_BhbThwxKlinWHb4',
    appId: '1:929254290761:ios:094254279175d0c3ac9698',
    messagingSenderId: '929254290761',
    projectId: 'financial-managememt-app',
    storageBucket: 'financial-managememt-app.appspot.com',
    iosClientId: '929254290761-tir739jo6iebet8gouif8ir9d0t60mvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodbankApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7rXS6TDV7jOiyj1q_BhbThwxKlinWHb4',
    appId: '1:929254290761:ios:094254279175d0c3ac9698',
    messagingSenderId: '929254290761',
    projectId: 'financial-managememt-app',
    storageBucket: 'financial-managememt-app.appspot.com',
    iosClientId: '929254290761-tir739jo6iebet8gouif8ir9d0t60mvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodbankApp',
  );
}
